# Generated by Django 4.1.1 on 2022-10-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('createtime', models.DateField()),
                ('lastlogintime', models.DateField()),
                ('role', models.SmallIntegerField(choices=[(0, '管理员'), (1, '超级管理员')], default=0)),
                ('token', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.IntegerField(choices=[(0, '禁用'), (1, '激活')], default=1)),
            ],
        ),
    ]
