# Generated by Django 4.1.1 on 2022-10-07 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_userlist_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserList',
            new_name='Users',
        ),
    ]
