# Generated by Django 4.1.1 on 2022-10-08 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_userlist_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='lastlogintime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
