# Generated by Django 4.1.1 on 2022-10-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_users_createtime_alter_users_lastlogintime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=256),
        ),
    ]
