# Generated by Django 4.1.1 on 2022-10-14 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_article_author_alter_article_categorys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
