# Generated by Django 4.1.1 on 2022-10-14 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='categorys',
            field=models.ManyToManyField(db_table='db_article2category', to='api.category'),
        ),
    ]
