# Generated by Django 4.1.1 on 2022-10-14 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_article_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
